### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by Catchii** [D3fe4ted/ParadiseC2#2]
Stuck at

        ╔════════════════════════════════════╗
        ║                                    ║
        ║        Successfully Screened       ║
        ║     ───────────────────────────    ║
        ║            ╔══════════╗            ║
        ╚════════════╣   LOGS   ╠════════════╝
                     ╚══════════╝

**Comment by Catchii** [comment]
i tried ubuntu and debian both dont work

**Comment by D3fe4ted** [comment]
Hi, did you try using RAW or TELNET to connect to it? Like this $ telnet  (server ip) and your port E.x; $ telnet 37.19.200.25 1337 or using putty.

**Comment by Catchii** [comment]
Hey i use Putty With Telnet Does not seem to work

**Comment by D3fe4ted** [comment]
Try Putty with RAW and if that does not work please send a screenshot of what happens after you connect with putty.

**Comment by Catchii** [comment]
How Do i use RAW With Putty My Console Is Just Empty.

**Comment by Catchii** [comment]
i just get this SSH-2.0-OpenSSH_8.9p1 Ubuntu-3

**Comment by Catchii** [comment]
> Try Putty with RAW and if that does not work please send a screenshot of what happens after you connect with putty.

![image](https://user-images.githubusercontent.com/86528346/192272601-fc4e52ef-b748-4f1a-be7a-999ea738c989.png)

**Comment by D3fe4ted** [comment]
It May be a firewall problem, are you using an open port on your server? Also don't from using port 23 or 22.

**Comment by D3fe4ted** [comment]
Seems to work fine for me

**Comment by Catchii** [comment]
> It May be a firewall problem, are you using an open port on your server? Also don't from using port 23 or 22.

Hey I Disabled My firewall And Im Using Port 1338
still does not work. could i maybe give u access to my vps so u could maybe find the issue? my discord is Catchii#0001

**Comment by D3fe4ted** [comment]
Sorry I don't use discord. Do you use any other chat service like telegram?
